### ISSUE TITLE
Found the course, just following/auditing

### ISSUE THREAD

**Issue by Bancherd-DeLong** [ekapolc/nlp_course#1]
Sawadee Krub:

May I follow/audit the course on my own?  If yes, since you are using jupyter notebook, I should be able to do the exercises/assignments on my own computer(Ubuntu 16.04, GeForce 1080 GPU)?

(I set up the free google-cloud trial account but they demanded that I put in US$35 to get one NVIDIA K80 GPU).

บรรเจิด เดลอง

**Comment by ekapolc** [comment]
Feel free to follow the course. You can do the assignments from github using your machine just fine. Some data  are already on gcloud VM, and thus not provided here. However, those are publicly available data like BEST. We also have all classes recorded and will release the videos at the end of the semester.

**Comment by Bancherd-DeLong** [comment]
Thank you, I have already downloaded the BEST data.
